// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StarWarsApi.Server.Data;

#nullable disable

namespace StarWarsApi.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260129205157_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StarWarsApi.Server.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Director")
                        .HasColumnType("text");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("integer");

                    b.Property<string>("OpeningCrawl")
                        .HasColumnType("text");

                    b.Property<string>("Producer")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.FilmCharacter", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.HasKey("FilmId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("FilmCharacters");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.FilmPlanet", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("integer");

                    b.Property<int>("PlanetId")
                        .HasColumnType("integer");

                    b.HasKey("FilmId", "PlanetId");

                    b.HasIndex("PlanetId");

                    b.ToTable("FilmPlanets");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.FilmSpecies", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("FilmId", "SpeciesId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("FilmSpecies");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.FilmStarship", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("integer");

                    b.Property<int>("StarshipId")
                        .HasColumnType("integer");

                    b.HasKey("FilmId", "StarshipId");

                    b.HasIndex("StarshipId");

                    b.ToTable("FilmStarships");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.FilmVehicle", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("FilmId", "VehicleId");

                    b.HasIndex("VehicleId");

                    b.ToTable("FilmVehicles");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BirthYear")
                        .HasColumnType("text");

                    b.Property<string>("EyeColor")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("HairColor")
                        .HasColumnType("text");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("HomeworldUrl")
                        .HasColumnType("text");

                    b.Property<int?>("Mass")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkinColor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Planet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Climate")
                        .HasColumnType("text");

                    b.Property<int?>("Diameter")
                        .HasColumnType("integer");

                    b.Property<string>("Gravity")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OrbitalPeriod")
                        .HasColumnType("integer");

                    b.Property<long?>("Population")
                        .HasColumnType("bigint");

                    b.Property<int?>("RotationPeriod")
                        .HasColumnType("integer");

                    b.Property<int?>("SurfaceWater")
                        .HasColumnType("integer");

                    b.Property<string>("Terrain")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.PlanetResident", b =>
                {
                    b.Property<int>("PlanetId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.HasKey("PlanetId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("PlanetResidents");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AverageHeight")
                        .HasColumnType("text");

                    b.Property<string>("AverageLifespan")
                        .HasColumnType("text");

                    b.Property<string>("Classification")
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<string>("EyeColors")
                        .HasColumnType("text");

                    b.Property<string>("HairColors")
                        .HasColumnType("text");

                    b.Property<int?>("HomeworldId")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkinColors")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HomeworldId");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.SpeciesPerson", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("PersonId", "SpeciesId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("SpeciesPerson");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Starship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long?>("CargoCapacity")
                        .HasColumnType("bigint");

                    b.Property<string>("Consumables")
                        .HasColumnType("text");

                    b.Property<decimal?>("CostInCredits")
                        .HasPrecision(18)
                        .HasColumnType("numeric(18,0)");

                    b.Property<int?>("Crew")
                        .HasColumnType("integer");

                    b.Property<double?>("HyperdriveRating")
                        .HasColumnType("double precision");

                    b.Property<double?>("Length")
                        .HasColumnType("double precision");

                    b.Property<int?>("MGLT")
                        .HasColumnType("integer");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("MaxAtmospheringSpeed")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Passengers")
                        .HasColumnType("integer");

                    b.Property<string>("StarshipClass")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Starships");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.StarshipPilot", b =>
                {
                    b.Property<int>("StarshipId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.HasKey("StarshipId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("StarshipPilots");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CargoCapacity")
                        .HasColumnType("text");

                    b.Property<string>("Consumables")
                        .HasColumnType("text");

                    b.Property<string>("CostInCredits")
                        .HasColumnType("text");

                    b.Property<string>("Crew")
                        .HasColumnType("text");

                    b.Property<string>("Length")
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("MaxAtmospheringSpeed")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Passengers")
                        .HasColumnType("text");

                    b.Property<string>("VehicleClass")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.VehiclePilot", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.HasKey("VehicleId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("VehiclePilots");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.FilmCharacter", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.Film", "Film")
                        .WithMany("FilmCharacters")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsApi.Server.Models.Person", "Person")
                        .WithMany("FilmCharacters")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.FilmPlanet", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.Film", "Film")
                        .WithMany("FilmPlanets")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsApi.Server.Models.Planet", "Planet")
                        .WithMany("FilmPlanets")
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Planet");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.FilmSpecies", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.Film", "Film")
                        .WithMany("FilmSpecies")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsApi.Server.Models.Species", "Species")
                        .WithMany("FilmSpecies")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.FilmStarship", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.Film", "Film")
                        .WithMany("FilmStarships")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsApi.Server.Models.Starship", "Starship")
                        .WithMany("FilmStarships")
                        .HasForeignKey("StarshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Starship");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.FilmVehicle", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.Film", "Film")
                        .WithMany("FilmVehicles")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsApi.Server.Models.Vehicle", "Vehicle")
                        .WithMany("FilmVehicles")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.PlanetResident", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.Person", "Person")
                        .WithMany("PlanetResidents")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsApi.Server.Models.Planet", "Planet")
                        .WithMany("PlanetResidents")
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Planet");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Species", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.Planet", "Homeworld")
                        .WithMany()
                        .HasForeignKey("HomeworldId");

                    b.Navigation("Homeworld");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.SpeciesPerson", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.Person", "Person")
                        .WithMany("SpeciesPeople")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsApi.Server.Models.Species", "Species")
                        .WithMany("SpeciesPeople")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.StarshipPilot", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.Person", "Person")
                        .WithMany("StarshipPilots")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsApi.Server.Models.Starship", "Starship")
                        .WithMany("StarshipPilots")
                        .HasForeignKey("StarshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Starship");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.VehiclePilot", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.Person", "Person")
                        .WithMany("VehiclePilots")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsApi.Server.Models.Vehicle", "Vehicle")
                        .WithMany("VehiclePilots")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Film", b =>
                {
                    b.Navigation("FilmCharacters");

                    b.Navigation("FilmPlanets");

                    b.Navigation("FilmSpecies");

                    b.Navigation("FilmStarships");

                    b.Navigation("FilmVehicles");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Person", b =>
                {
                    b.Navigation("FilmCharacters");

                    b.Navigation("PlanetResidents");

                    b.Navigation("SpeciesPeople");

                    b.Navigation("StarshipPilots");

                    b.Navigation("VehiclePilots");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Planet", b =>
                {
                    b.Navigation("FilmPlanets");

                    b.Navigation("PlanetResidents");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Species", b =>
                {
                    b.Navigation("FilmSpecies");

                    b.Navigation("SpeciesPeople");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Starship", b =>
                {
                    b.Navigation("FilmStarships");

                    b.Navigation("StarshipPilots");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Vehicle", b =>
                {
                    b.Navigation("FilmVehicles");

                    b.Navigation("VehiclePilots");
                });
#pragma warning restore 612, 618
        }
    }
}
