// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StarWarsApi.Server.Data;

#nullable disable

namespace StarWarsApi.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260202183200_AddCustomPilotToStarship")]
    partial class AddCustomPilotToStarship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Director")
                        .HasColumnType("text");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("integer");

                    b.Property<string>("OpeningCrawl")
                        .HasColumnType("text");

                    b.Property<string>("Producer")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.FilmCharacter", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.HasKey("FilmId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("FilmCharacters");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.FilmPlanet", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("integer");

                    b.Property<int>("PlanetId")
                        .HasColumnType("integer");

                    b.HasKey("FilmId", "PlanetId");

                    b.HasIndex("PlanetId");

                    b.ToTable("FilmPlanets");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.FilmSpecies", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("FilmId", "SpeciesId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("FilmSpecies");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.FilmStarship", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("integer");

                    b.Property<int>("StarshipId")
                        .HasColumnType("integer");

                    b.HasKey("FilmId", "StarshipId");

                    b.HasIndex("StarshipId");

                    b.ToTable("FilmStarships");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.FilmVehicle", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("FilmId", "VehicleId");

                    b.HasIndex("VehicleId");

                    b.ToTable("FilmVehicles");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Fleet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Fleets");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.FleetStarship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FleetId")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("StarshipId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StarshipId");

                    b.HasIndex("FleetId", "StarshipId")
                        .IsUnique();

                    b.ToTable("FleetStarships");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BirthYear")
                        .HasColumnType("text");

                    b.Property<string>("EyeColor")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("HairColor")
                        .HasColumnType("text");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeworldId")
                        .HasColumnType("integer");

                    b.Property<int?>("Mass")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkinColor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HomeworldId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Planet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Climate")
                        .HasColumnType("text");

                    b.Property<int?>("Diameter")
                        .HasColumnType("integer");

                    b.Property<string>("Gravity")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OrbitalPeriod")
                        .HasColumnType("integer");

                    b.Property<long?>("Population")
                        .HasColumnType("bigint");

                    b.Property<int?>("RotationPeriod")
                        .HasColumnType("integer");

                    b.Property<int?>("SurfaceWater")
                        .HasColumnType("integer");

                    b.Property<string>("Terrain")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.PlanetResident", b =>
                {
                    b.Property<int>("PlanetId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.HasKey("PlanetId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("PlanetResidents");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AverageHeight")
                        .HasColumnType("text");

                    b.Property<string>("AverageLifespan")
                        .HasColumnType("text");

                    b.Property<string>("Classification")
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<string>("EyeColors")
                        .HasColumnType("text");

                    b.Property<string>("HairColors")
                        .HasColumnType("text");

                    b.Property<int?>("HomeworldId")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkinColors")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HomeworldId");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.SpeciesPerson", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("PersonId", "SpeciesId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("SpeciesPerson");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Starship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaseStarshipId")
                        .HasColumnType("integer");

                    b.Property<long?>("CargoCapacity")
                        .HasColumnType("bigint");

                    b.Property<string>("Consumables")
                        .HasColumnType("text");

                    b.Property<decimal?>("CostInCredits")
                        .HasPrecision(18)
                        .HasColumnType("numeric(18,0)");

                    b.Property<int?>("Crew")
                        .HasColumnType("integer");

                    b.Property<int?>("CustomPilotId")
                        .HasColumnType("integer");

                    b.Property<double?>("HyperdriveRating")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCatalog")
                        .HasColumnType("boolean");

                    b.Property<double?>("Length")
                        .HasColumnType("double precision");

                    b.Property<int?>("MGLT")
                        .HasColumnType("integer");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("MaxAtmospheringSpeed")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerUserId")
                        .HasColumnType("text");

                    b.Property<int?>("Passengers")
                        .HasColumnType("integer");

                    b.Property<string>("StarshipClass")
                        .HasColumnType("text");

                    b.Property<string>("SwapiUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BaseStarshipId");

                    b.HasIndex("CargoCapacity");

                    b.HasIndex("CostInCredits");

                    b.HasIndex("Crew");

                    b.HasIndex("CustomPilotId");

                    b.HasIndex("Length");

                    b.HasIndex("Manufacturer");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("Passengers");

                    b.HasIndex("StarshipClass");

                    b.HasIndex("SwapiUrl")
                        .IsUnique();

                    b.ToTable("Starships");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.StarshipPilot", b =>
                {
                    b.Property<int>("StarshipId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.HasKey("StarshipId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("StarshipPilots");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CargoCapacity")
                        .HasColumnType("text");

                    b.Property<string>("Consumables")
                        .HasColumnType("text");

                    b.Property<string>("CostInCredits")
                        .HasColumnType("text");

                    b.Property<string>("Crew")
                        .HasColumnType("text");

                    b.Property<string>("Length")
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("MaxAtmospheringSpeed")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Passengers")
                        .HasColumnType("text");

                    b.Property<string>("VehicleClass")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.VehiclePilot", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.HasKey("VehicleId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("VehiclePilots");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsApi.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.FilmCharacter", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.Film", "Film")
                        .WithMany("FilmCharacters")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsApi.Server.Models.Person", "Person")
                        .WithMany("FilmCharacters")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.FilmPlanet", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.Film", "Film")
                        .WithMany("FilmPlanets")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsApi.Server.Models.Planet", "Planet")
                        .WithMany("FilmPlanets")
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Planet");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.FilmSpecies", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.Film", "Film")
                        .WithMany("FilmSpecies")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsApi.Server.Models.Species", "Species")
                        .WithMany("FilmSpecies")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.FilmStarship", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.Film", "Film")
                        .WithMany("FilmStarships")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsApi.Server.Models.Starship", "Starship")
                        .WithMany("FilmStarships")
                        .HasForeignKey("StarshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Starship");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.FilmVehicle", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.Film", "Film")
                        .WithMany("FilmVehicles")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsApi.Server.Models.Vehicle", "Vehicle")
                        .WithMany("FilmVehicles")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Fleet", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.FleetStarship", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.Fleet", "Fleet")
                        .WithMany("FleetStarships")
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsApi.Server.Models.Starship", "Starship")
                        .WithMany()
                        .HasForeignKey("StarshipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fleet");

                    b.Navigation("Starship");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Person", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.Planet", "Homeworld")
                        .WithMany("HomeworldPeople")
                        .HasForeignKey("HomeworldId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Homeworld");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.PlanetResident", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.Person", "Person")
                        .WithMany("PlanetResidents")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsApi.Server.Models.Planet", "Planet")
                        .WithMany("PlanetResidents")
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Planet");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Species", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.Planet", "Homeworld")
                        .WithMany()
                        .HasForeignKey("HomeworldId");

                    b.Navigation("Homeworld");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.SpeciesPerson", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.Person", "Person")
                        .WithMany("SpeciesPeople")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsApi.Server.Models.Species", "Species")
                        .WithMany("SpeciesPeople")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Starship", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.Starship", "BaseStarship")
                        .WithMany()
                        .HasForeignKey("BaseStarshipId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StarWarsApi.Server.Models.Person", "CustomPilot")
                        .WithMany()
                        .HasForeignKey("CustomPilotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StarWarsApi.Server.Models.ApplicationUser", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BaseStarship");

                    b.Navigation("CustomPilot");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.StarshipPilot", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.Person", "Person")
                        .WithMany("StarshipPilots")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsApi.Server.Models.Starship", "Starship")
                        .WithMany("StarshipPilots")
                        .HasForeignKey("StarshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Starship");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.VehiclePilot", b =>
                {
                    b.HasOne("StarWarsApi.Server.Models.Person", "Person")
                        .WithMany("VehiclePilots")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsApi.Server.Models.Vehicle", "Vehicle")
                        .WithMany("VehiclePilots")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Film", b =>
                {
                    b.Navigation("FilmCharacters");

                    b.Navigation("FilmPlanets");

                    b.Navigation("FilmSpecies");

                    b.Navigation("FilmStarships");

                    b.Navigation("FilmVehicles");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Fleet", b =>
                {
                    b.Navigation("FleetStarships");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Person", b =>
                {
                    b.Navigation("FilmCharacters");

                    b.Navigation("PlanetResidents");

                    b.Navigation("SpeciesPeople");

                    b.Navigation("StarshipPilots");

                    b.Navigation("VehiclePilots");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Planet", b =>
                {
                    b.Navigation("FilmPlanets");

                    b.Navigation("HomeworldPeople");

                    b.Navigation("PlanetResidents");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Species", b =>
                {
                    b.Navigation("FilmSpecies");

                    b.Navigation("SpeciesPeople");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Starship", b =>
                {
                    b.Navigation("FilmStarships");

                    b.Navigation("StarshipPilots");
                });

            modelBuilder.Entity("StarWarsApi.Server.Models.Vehicle", b =>
                {
                    b.Navigation("FilmVehicles");

                    b.Navigation("VehiclePilots");
                });
#pragma warning restore 612, 618
        }
    }
}
